---
abstract: "A Modern Perl interface to CyberSource's SOAP API."
author:
  - 'Amiri Barksdale <amiri@metalabel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Checkout-CyberSource-SOAP
recommends: {}
requires:
  Business::CreditCard: 0
  Crypt::SSLeay: 0
  Moose: 0
  SOAP::Lite: 0
  Time::HiRes: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/amiri/Checkout--CyberSource--SOAP
version: 0.02
